import { createApi, fetchBaseQuery } from "@reduxjs/toolkit/query/react";

export const carWashBillApi = createApi({
  reducerPath: "carWashApi",
 
  baseQuery: fetchBaseQuery({ baseUrl: "https://alhayyat-backend.onrender.com/" }),
  // baseQuery: fetchBaseQuery({ baseUrl: "http://localhost:5000/" }),

  endpoints: (builder) => ({

    // ====================================================================================
    // 🟨 🚗 CAR WASH API
    // ====================================================================================
    submitCarWashBill: builder.mutation({
      query: (body) => ({
        url: "generate-bill",
        method: "POST",
        body: { records: body },
      }),
    }),

    getAllBills: builder.query({
      query: (filter) => `carWash-bills?filter=${filter}`,
    }),

    getCarWashBillByDate: builder.query({
      query: (startDate) =>
        startDate
          ? `carWash-bill-date?date=${new Date(startDate).toISOString()}`
          : "carWash-bill-date",
    }),

    updateCommissionStatus: builder.mutation({
      query: (data) => ({
        url: "commission-paid",
        method: "POST",
        body: data, // expects { _id }
      }),
    }),

    deleteBill: builder.mutation({
      query: (id) => ({
        url: `carWash-bill-delete/${id}`,
        method: "DELETE",
      }),
    }),

    updateBill: builder.mutation({
      query: ({ id, ...body }) => ({
        url: `carWash-bills-update/${id}`,
        method: "PUT",
        body,
      }),
    }),

    // ====================================================================================
    // 🟨 🧽 DETAILING STUDIO API
    // ====================================================================================
    getAllBillsDetailing: builder.query({
      query: (filter) => `detailing/bills?filter=${filter}`,
    }),

    getDetailingBillByDate: builder.query({
      query: (startDate) =>
        startDate
          ? `detailing/bills-by-date?date=${new Date(startDate).toISOString()}`
          : "detailing/bills-by-date",
    }),

    updateCommissionStatusDetailing: builder.mutation({
      query: (data) => ({
        url: "detailing/update-commission",
        method: "PUT",
        body: data, // expects { _id }
      }),
    }),

    // ====================================================================================
    // 🟨 🛢️ OIL SHOP (PRODUCTS & SALES)
    // ====================================================================================
    addProduct: builder.mutation({
      query: (body) => ({
        url: "add-product",
        method: "POST",
        body,
      }),
    }),

    getAllProducts: builder.query({
      query: () => "all-product",
    }),

    saleProduct: builder.mutation({
      query: (body) => ({
        url: "sale-product",
        method: "POST",
        body,
      }),
    }),

    getSaleProductRecord: builder.query({
      query: (id) => `sale-product/${id}`,
    }),

    getAllSales: builder.query({
      query: () => "all-sales",
    }),

    // ====================================================================================
    // 🟨 🧰 ACCESSORIES API
    // ====================================================================================
    addAccessoriesItem: builder.mutation({
      query: (body) => ({
        url: "add-accessories-item",
        method: "POST",
        body,
      }),
    }),

    getAllAccessoriesItems: builder.query({
      query: () => "all-accessories",
    }),

    getAllSaleAccessories: builder.query({
      query: () => "all-sale-accessories",
    }),

    // ====================================================================================
    // 🟨 👥 EMPLOYEES API
    // ====================================================================================
    addEmployee: builder.mutation({
      query: (body) => ({
        url: "employees",
        method: "POST",
        body,
      }),
    }),

    getAllEmployees: builder.query({
      query: () => "employees",
    }),

    getEmployeeById: builder.query({
      query: (id) => `employees/${id}`,
    }),

    deleteEmployee: builder.mutation({
      query: (id) => ({
        url: `employees/${id}`,
        method: "DELETE",
      }),
    }),

    updateEmployee: builder.mutation({
      query: ({ id, ...body }) => ({
        url: `employees/${id}`,
        method: "PUT",
        body,
      }),
    }),
  }),
});

// ====================================================================================
// 🟨 Exported Hooks (auto-generated by RTK Query)
// ====================================================================================

export const {
  //🟨 Car Wash
  useSubmitCarWashBillMutation,
  useGetAllBillsQuery,
  useGetCarWashBillByDateQuery,
  useUpdateCommissionStatusMutation,
  useDeleteBillMutation,
  useUpdateBillMutation,

  //🟨 Detailing
  useGetAllBillsDetailingQuery,
  useGetDetailingBillByDateQuery,
  useUpdateCommissionStatusDetailingMutation,

  //🟨 Oil Shop
  useAddProductMutation,
  useGetAllProductsQuery,
  useSaleProductMutation,
  useGetSaleProductRecordQuery,
  useGetAllSalesQuery,

  //🟨 Accessories
  useAddAccessoriesItemMutation,
  useGetAllAccessoriesItemsQuery,
  useGetAllSaleAccessoriesQuery,

  //🟨 Employees
  useAddEmployeeMutation,
  useGetAllEmployeesQuery,
  useGetEmployeeByIdQuery,
  useUpdateEmployeeMutation,
  useDeleteEmployeeMutation,
} = carWashBillApi;
